prueba_homepage:
    path:     /
    defaults: { _controller: PruebaBundle:Default:index }

prueba_nombre:
    path:     /nombre/{nPila}
    defaults: { _controller: PruebaBundle:Default:nombre } 
prueba_contactar:
    path:     /contactar/{lugar}
    defaults: { _controller: PruebaBundle:Default:contactar, lugar:"Sevilla" } 
prueba_contactarVlc:
    path:     /contactarVlc
    defaults: { _controller: PruebaBundle:Default:contactarVlc} 
prueba_nombreR:
    path:     /nombreR/{nPila}
    defaults: { _controller: PruebaBundle:Default:nombreR } 

prueba_nombre_sinParametros:
    path:     /nombre/
    defaults: { _controller: PruebaBundle:Default:nombre }     
prueba_redireccion:
    path:     /redireccion/
    defaults: { _controller: PruebaBundle:Default:redireccion }    
all_eventos:
    path:     /eventos/all
    defaults: { _controller: PruebaBundle:Eventos:all }        