<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYwfg5pa\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYwfg5pa/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerYwfg5pa.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerYwfg5pa\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerYwfg5pa\appProdProjectContainer(array(
    'container.build_hash' => 'Ywfg5pa',
    'container.build_id' => 'de1ec7aa',
    'container.build_time' => 1517819049,
));
