<?php

namespace EmpresaBundle\Repository;

/**
 * TipoEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEmpresaRepository extends \Doctrine\ORM\EntityRepository
{
}
