<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0lnkzo9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0lnkzo9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0lnkzo9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0lnkzo9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0lnkzo9\appDevDebugProjectContainer(array(
    'container.build_hash' => '0lnkzo9',
    'container.build_id' => 'cc778f8e',
    'container.build_time' => 1518082024,
));
